### ISSUE TITLE
本人不会docker,购置了一个群晖918,不知道怎么使用这个...

### ISSUE THREAD

**Issue by qiumomo** [john-shine/Docker-CodeWeavers_CrossOver-VNC#10]
本人不会docker,购置了一个群晖918,不知道怎么使用这个...
用vnc连接的时候,提示需要输入密码,可是我也没有设置密码...

**Comment by qiumomo** [comment]
不行的,我用tightvnc,提示我空密码

**Comment by john-shine** [comment]
在群晖docker中，进入“容器”->选择百度云并查看"详情"->在“环境变量”一栏看是否有vnc_password这个变量名，如果有就使用改密码连接，没有尝试下面的软件连接，我测试过空密码连接没有问题：
https://www.realvnc.com/en/connect/download/viewer/windows/
