### ISSUE TITLE
tightvnc连接到容器，提示需要购买授权。。。容器无法登陆

### ISSUE THREAD

**Issue by f0ghua** [john-shine/Docker-CodeWeavers_CrossOver-VNC#11]

**Comment by f0ghua** [comment]
![2018-06-25_145133](https://user-images.githubusercontent.com/10104613/41834566-53aae988-7887-11e8-9e85-18f57d4f6d9f.png)

**Comment by john-shine** [comment]
软件是共享软件，编译的时间太久，已超出试用时间，你可以自行编译镜像
中文教程：http://www.runoob.com/docker/docker-build-command.html
英文教程：https://docs.docker.com/engine/reference/builder/#usage
