### ISSUE TITLE
能装最新版百度云客户端吗？

### ISSUE THREAD

**Issue by sukeyisme** [john-shine/Docker-CodeWeavers_CrossOver-VNC#15]
能装最新版百度云客户端吗？

**Comment by john-shine** [comment]
考虑到百度云核心功能是下载，目前版本能满足大部分用户的需求，没有多大更新的必要。新版本有什么新功能吸引到你呢？

**Comment by sukeyisme** [comment]
推送下载，你这个会经常挂。

**Comment by john-shine** [comment]
推送功能不稳定主要和crossover对api兼容性有关，我尝试下安装新版本，看推送功能能不能用吧

**Comment by welpher** [comment]
请问crossover要在哪里买呢

**Comment by john-shine** [comment]
@welpher 不建议购买，现在已经被国内某厂商代理了，而且还死贵

**Comment by ToughLife** [comment]
docker新手，有个疑问没想通。既然docker是不保存容器状态的，那对于一个试用版的软件，是不是可以一直试用下去？就好像在vmware里设置了一个snapshot，试用期一到，我就恢复到那个snapshot。
我的想法是，下载你给的容器后，装完windows软件后commit一下。以后每次运行docker时，都不保存状态。这样我是不是可以一直把装了windows软件的容器用下去？crossover一直不会过期？

**Comment by john-shine** [comment]
@ToughLife docker镜像是不会保存容器的运行状态，但是运行容器的时候，容器存在时间自动和host同步的机制，也就是说容器中的软件还是会因为时间变化而过期。不过也有办法做到在容器中使用fake time，使用完全不同的时间，你可以试试下这个方法

**Comment by ToughLife** [comment]
好的，非常感谢！

**Comment by john-shine** [comment]
目前已升级为linux版，为当前最新版本
