### ISSUE TITLE
VNC登录后， 没有百度云出现，一片灰白的界面

### ISSUE THREAD

**Issue by ZhaoqiangCn** [john-shine/Docker-CodeWeavers_CrossOver-VNC#16]

**Comment by ZhaoqiangCn** [comment]
johnshine/baidunetdisk-crossover-vnc latest ,VNC viewer

**Comment by newdee** [comment]
这个就是crossover为了卖产品弄的吧，进去就提示过期几百天要注册购买

**Comment by john-shine** [comment]
@newdee 纯个人项目，和CrossOver官方没有关系，过期需要自行来编译解决。
