### ISSUE TITLE
使用docker hub镜像提示CrossOver已经超过使用期限

### ISSUE THREAD

**Issue by daoying007** [john-shine/Docker-CodeWeavers_CrossOver-VNC#17]
1、使用docker hub镜像提示CrossOver已经超过使用期限

2、自己重新用源码build镜像后，进去后纯灰屏，无法做任何操作，截图看附件

**Comment by jonecns** [comment]
> 1、使用docker hub镜像提示CrossOver已经超过使用期限
> 
> 2、自己重新用源码build镜像后，进去后纯灰屏，无法做任何操作，截图看附件

同样的问题，请问现在解决了吗？

**Comment by john-shine** [comment]
1、超过使用期限要到5.1期间才有时间解决
2、根目录下的Dockerfile是基础镜像，如果要编译具体软件，需要再次到相应目录下的Dockerfile编译

**Comment by john-shine** [comment]
@daoying007 @jonecns 最新版已经更新
