### ISSUE TITLE
docker run后，不能直接使用vnc登录图形界面

### ISSUE THREAD

**Issue by Zyx-A** [john-shine/Docker-CodeWeavers_CrossOver-VNC#2]
docker run后，不能直接使用vnc登录图形界面，无论是否执行“-e vnc_password=your_password”。
如果需要正常使用，要补充执行如下步骤：
sudo docker exec -it 容器名 /bin/bash
ip address              # 查看容器IP
vncserver -kill :1    # 关闭已自动开启的vnc会话
vncpasswd            # 输入两次新的密码，及可选的只读密码。
vncserver :1          # 启动vnc会话

**Comment by john-shine** [comment]
理论上已经绑定了host的指定端口，使用127.0.0.1 ip即可连接；默认密码是空，请问连接失败提示什么消息

**Comment by Zyx-A** [comment]
使用vncviewer时，提示：too many security failures

**Comment by john-shine** [comment]
![2017-11-16_18-51-23](https://user-images.githubusercontent.com/6376135/32887593-6114cd72-caff-11e7-9525-90890e46b677.jpg)
使用macos和linux版本vncviewer均连接正常

**Comment by john-shine** [comment]
too many security failures错误，可看看下面的链接
[https://support.realvnc.com/knowledgebase/article/View/244/1/too-many-security-failures](url)

**Comment by Zyx-A** [comment]
我刚刚又重试了一下，无密码登录，vncviewer确实可以了，不过Ubuntu的Remmina还是不行。如果加上了参数“-e vnc_password=your_password”，则vncviewer和Remmina都不行。

**Comment by vanxv** [comment]
crossover need unlock key

**Comment by qfsf0220** [comment]
请教一下，在vnc登录百度账号时， 出现 **网络异常[1]** ，具体如何解决呢？主机docker都可以正常访问网络。

**Comment by qfsf0220** [comment]
@vanxv 可以搜索一个 winewrapper.exe.so  替换/opt/cxoffice/lib/wine/winewrapper.exe.so

**Comment by john-shine** [comment]
@qfsf0220 
1、先ping一下网络，看下是不是主机网络没有连通
2、尝试使用--net host参数启动docker镜像
3、删除容器，重新部署
4、docker部分版本有bug，尝试升级

**Comment by john-shine** [comment]
fixed
