### ISSUE TITLE
百度可以考虑下集成网页版vnc

### ISSUE THREAD

**Issue by sukeyisme** [john-shine/Docker-CodeWeavers_CrossOver-VNC#20]

**Comment by john-shine** [comment]
已集成，可配合套件使用：https://github.com/john-shine/synology-baiduNetdisk-package

**Comment by sukeyisme** [comment]
vnc 密码和路径设置是不是无效了？

**Comment by john-shine** [comment]
@sukeyisme  按道理是密码和路径设置是有效的，只是套件没有地方设置
