### ISSUE TITLE
非法文件名

### ISSUE THREAD

**Issue by chyaww** [john-shine/Docker-CodeWeavers_CrossOver-VNC#24]
下载了一个文件，再下载任何文件就出现非法文件名的提示，无法下载了

**Comment by john-shine** [comment]
@chyaww  优先使用群晖套件，应该没有问题。如果自己运行镜像，可以运行docker exec -it ${container_id} /bin/bash ，进入docker容器中运行 ls -la , 看下下载目录的权限，回复在issue中，我看下

**Comment by chyaww** [comment]
@john-shine 使用群晖的docker套件运行的，下载目录权限777，看了没问题的~

**Comment by john-shine** [comment]
群晖套件是这个 https://github.com/john-shine/synology-baiduNetdisk-package

**Comment by chyaww** [comment]
@john-shine 可以了，还不限速^ ^ 我原来是直接在docker中运行，出现了非法文件名这个问题

**Comment by john-shine** [comment]
OK
