### ISSUE TITLE
大佬有时间的话可否同步一下最新的客户端？

### ISSUE THREAD

**Issue by opencasting** [john-shine/Docker-CodeWeavers_CrossOver-VNC#25]
我看百度官网linux版客户端更新了，

**Comment by john-shine** [comment]
晚上更新下

**Comment by john-shine** [comment]
@opencasting 已更新

**Comment by klgd** [comment]
请问更新的是多少版本？ 我这边刚装的还是2.0.3（现在官方最新是3.0.1）

**Comment by john-shine** [comment]
同https://github.com/john-shine/synology-baiduNetdisk-package/issues/1
