### ISSUE TITLE
反复登录问题

### ISSUE THREAD

**Issue by huojicache** [john-shine/Docker-CodeWeavers_CrossOver-VNC#27]
挂机下载一定时间后会出现重新登录，更长时间例如隔夜后重新登录进去任务没有速度要暂停再开始。
反复登录问题可以解决吗？

**Comment by john-shine** [comment]
@huojicache 出现重新登录，有两种可能：
一、登录的客户端过多，导致之前登录的客户端强制下线，这属于百度做的安全策略
二、容器或进程重启了。运行docker ps, 看下容器运行了多长时间，时间短可能是容器重启了。运行docker exec -it ${container_id} /bin/bash进入容器，然后运行ps ax|grep -i baidunetdisk$|grep -v grep, 记录下进程pid，下次出现重新登录时看下pid有没有变化，变化说明进程重启了，可能是客户端崩溃了

**Comment by huojicache** [comment]
经过4天左右的使用，下载单文件19g有出现反复登录情况(客户端确定只登录了这一个，我用的群晖没有容器崩溃日志，进程pid我今天做了记录根据使用情况再做回复)。
下载单文件3g左右并没反复登录情况，似乎更接近你说的进程重启。
使用过程中出现了新的问题，会出现多个重复内容的提示框，提示内容是暂不支持分享下载链接(没记错的话)，手动关掉并没有发现有啥影响

**Comment by huojicache** [comment]
@huojicache 
![崩溃](https://user-images.githubusercontent.com/37629177/71897875-c77bff80-3192-11ea-8d21-b3a6907e70bf.PNG)
确实是进程崩溃引起的,崩溃的进程如图所示

以下是新问题的截图
![image](https://user-images.githubusercontent.com/37629177/71897930-f72b0780-3192-11ea-966c-de36f92a2e99.png)

**Comment by john-shine** [comment]
崩溃的问题，可以看下系统内存资源是否充足，运行镜像时候是否对内存资源有限制
如果这两个方面没问题，比较大的可能是官方客户端的问题，可以提交到百度官方开发人员进行反馈，日志路径：/var/log/baidunetdisk.log

"暂不支持下载分享文件"的提示，参照提示查看文件是不是分享类型文件，更多的解答需要向百度开发求证

**Comment by huojicache** [comment]
我的群晖16g内存,容器内存是动态的没有限制.
我看了下日志里面有大量相同错误提示
第1个错误如下
 PacketManager::process_keyexchangepacket_return server error cookie=11397, error=100003
第2个错误如下
 ASSERT FAIL @ /home/scmbuild/workspaces_cluster/baidu.netdisk.pc-browserengine/baidu/netdisk/pc-browserengine/source/browserengine/pushchannel/protocolpacket/packet_check.cpp(130)
ConnectionManager::on_disconnect error[End of file] retry connect

我看到可到客户端提示有版本更新,目前版本2.0.3,最新3.01
我用Ubuntu装了百度官网下载的最新版,关于中依然是2.0.3发现更新版本为3.0.1.这应该是百度的锅
使用了一天暂时没发先同样问题,还需要多测几天.后续再做答复
Ubuntu用的是docker Ubuntu vnc版

**Comment by huojicache** [comment]
还是那个单文件19g已经下载完毕，在新环境测试过程中没有弹出分享链接问题，没有客户端重启问题。

**Comment by john-shine** [comment]
看日志是客户端连接网络出错了，估计是客户端的bug。这个issue先关闭了，另外群晖直接用套件安装包更方便：https://github.com/john-shine/synology-baiduNetdisk-package
