### ISSUE TITLE
未下载任务时，无故占用上传带宽

### ISSUE THREAD

**Issue by psychopasss** [john-shine/Docker-CodeWeavers_CrossOver-VNC#28]

**Comment by john-shine** [comment]
这个属于官方客户端的行为，和镜像本身没有关系，可以看下知乎相关讨论：
https://www.zhihu.com/search?type=content&q=%E7%99%BE%E5%BA%A6%E4%BA%91%20%E5%81%B7%E5%81%B7%20%E4%B8%8A%E4%BC%A0

**Comment by psychopasss** [comment]
有解决方案吗？





------------------ 原始邮件 ------------------
发件人: John Shine <notifications@github.com&gt;
发送时间: 2020年1月7日 21:26
收件人: john-shine/Docker-CodeWeavers_CrossOver-VNC <Docker-CodeWeavers_CrossOver-VNC@noreply.github.com&gt;
抄送: Psycho Pass <308989414@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[john-shine/Docker-CodeWeavers_CrossOver-VNC] 未下载任务时，无故占用上传带宽 (#28)




这个属于官方客户端的行为，和镜像本身没有关系，可以看下知乎相关讨论：
https://www.zhihu.com/search?type=content&amp;q=%E7%99%BE%E5%BA%A6%E4%BA%91%20%E5%81%B7%E5%81%B7%20%E4%B8%8A%E4%BC%A0

**Comment by john-shine** [comment]
删除下载目录中已下载的文件试试
