### ISSUE TITLE
冒昧请教一下：既然跑了 vnc 和 fluxbox 了，为何 Dockerfile 还要 Crossover ?

### ISSUE THREAD

**Issue by bao3** [john-shine/Docker-CodeWeavers_CrossOver-VNC#29]
我自己也想弄一个这样 web vnc + application 的。看到你的 Dockerfile 后，由此疑惑，所以请教一下。

**Comment by john-shine** [comment]
运行Windows应用才需要，并不是所有的Dockerfile都包含的。如果不需要运行Windows应用，可以去掉这部分。
