### ISSUE TITLE
将容器中默认下载目录绑定到host上的补充教程

### ISSUE THREAD

**Issue by Zyx-A** [john-shine/Docker-CodeWeavers_CrossOver-VNC#3]
解决将容器中默认下载目录绑定到host上后，下载时并没有按照预期将文件存储到host中。及百度云不能修改下载存放目录。

如果要将容器中默认下载目录绑定到host上，在创建容器时，就需要带上参数：“-v /path/to/download/folder:/mnt/drive_d”
除此之外，还需要在使用VNC登录容器，并执行下载任务前，在host上执行如下修改：
$ sudo chown 100:0 /path/to/download/folder
然后再VNC登录到容器，并执行下载任务。此时就会按照预期将文件存储到host中。

如果需要将 /path/to/download/folder 目录权限改回（如 ~/下载 这样的目录），则需待百度云客户端成功创建 BaiduNetdiskDownload 文件夹后，就可以将原来的 /path/to/download/folder 目录权限改回，参考命令：
$ sudo chown 1000:1000 /path/to/download/folder

============================================================================

以上步骤可以简化为（我没亲测过，但理论上是可行的）：
1、在创建容器时，就需要带上参数：“-v /path/to/download/folder:/mnt/drive_d”
2、在host上创建目录：
$ mkdir /path/to/download/folder/BaiduNetdiskDownload
3、修改host上 BaiduNetdiskDownload 目录的权限：
$ sudo chown 100:0 /path/to/download/folder/BaiduNetdiskDownload
4、登录VNC，并使用百度云下载

**Comment by john-shine** [comment]
恩，这个问题已经发现并在本地修复，wine读取不到D盘。你的建议可行，更改/path/to/download/folder所有者即可。修改权限过程打算放在xstartp中做，明天发布上去

**Comment by john-shine** [comment]
非常抱歉，事多更新晚了。问题已修复
