### ISSUE TITLE
docker跑起来后 VNC连进去只有一片白

### ISSUE THREAD

**Issue by 81pla** [john-shine/Docker-CodeWeavers_CrossOver-VNC#30]
docker跑起来后 VNC连进去只有一片白

这个应该怎么办

**Comment by john-shine** [comment]
运行命令docker ps得到container_id
运行命令docker exec -it $container_id /bin/bash 进入container中的bash
运行需要执行的程序，看是否有界面或者有报错信息

**Comment by 81pla** [comment]
自己docker网络问题。已正常
