### ISSUE TITLE
重启docker后会卡在百度网盘载入界面

### ISSUE THREAD

**Issue by bowenqiang** [john-shine/Docker-CodeWeavers_CrossOver-VNC#31]
重启docker后然后通过vnc连接后会发现客户端卡住百度网盘登录的载入界面，请问如何解决？

![Screen Shot 2020-03-04 at 12 38 59 AM](https://user-images.githubusercontent.com/11279043/75797761-9265e500-5db0-11ea-8b0e-475ea52df03d.png)

**Comment by john-shine** [comment]
删除/home/baidu/baidunetdisk目录下的数据，然后重启docker，重新登录
