### ISSUE TITLE
进入 VNC 之后无法登陆，只出现一片空白

### ISSUE THREAD

**Issue by Sheldonsix** [john-shine/Docker-CodeWeavers_CrossOver-VNC#34]
清除数据和重启都试过了，如图 
![image](https://user-images.githubusercontent.com/42886406/79445449-4644cc00-800f-11ea-8c65-41d84ec31b26.png)

**Comment by john-shine** [comment]
这个应该是你docker内网络的原因

**Comment by Sheldonsix** [comment]
> 这个应该是你docker内网络的原因

感谢回复，不过我在两台机子都尝试了，都会出现这种情况

**Comment by john-shine** [comment]
`cat /var/log/baidunetdisk.log`

看下容器内的日志

**Comment by Sheldonsix** [comment]
你好，这是日志中的内容
```
(node:73) ExperimentalWarning: The dns.promises API is experimental
get_adapter_mac interface num = 2
get_adapter_mac mac=0242ac110004
CreatePCGuid::get_cpu_id 0000000B756E654749656E696C65746E
browser engine version: 1.0.0.2
minos agent version:1.2.2.2
/tmp
kernel version: 2.1.23.2
curl_easy_perform error[35]
DeviceManager::on_device_register_return http_code=0 client_error=1 server_error=99999
TcpConnection::on_connection addr=(202.108.23.113) failed Connection timed out code=110
ConnectionManager::on_connect error[Connection timed out] retry connect
PacketManager::process_keyexchangepacket_return server error cookie=1, error=100003
ASSERT FAIL @ /home/scmbuild/workspaces_cluster/baidu.netdisk.pc-browserengine/baidu/netdisk/pc-browserengine/source/browserengine/pushchannel/protocolpacket/packet_manager.cpp(422)
ConnectionManager::on_disconnect error[End of file] retry connect
ConnectionManager::on_disconnect error[End of file] retry connect
PacketManager::process_keyexchangepacket_return server error cookie=24, error=100003
ASSERT FAIL @ /home/scmbuild/workspaces_cluster/baidu.netdisk.pc-browserengine/baidu/netdisk/pc-browserengine/source/browserengine/pushchannel/protocolpacket/packet_manager.cpp(422)
```

**Comment by john-shine** [comment]
> ConnectionManager::on_connect error[Connection timed out] retry connect

确实是网络问题，连不上百度服务器

**Comment by Sheldonsix** [comment]
> > ConnectionManager::on_connect error[Connection timed out] retry connect
> 
> 确实是网络问题，连不上百度服务器

请问有解决办法吗，还是要等百度服务器的反应

**Comment by john-shine** [comment]
先在docker容器内运行

`curl -v https://pan.baidu.com`

看下网络有没有响应。没响应的话，百度或谷歌搜一下这方面的排查文章

**Comment by Sheldonsix** [comment]
> 先在docker容器内运行
> 
> `curl -v https://pan.baidu.com`
> 
> 看下网络有没有响应。没响应的话，百度或谷歌搜一下这方面的排查文章

输入命令之后有反应，是一大串 HTML 的代码

**Comment by john-shine** [comment]
说明外网是通的，比较有可能的是百度云服务器出现了问题
![2020-04-16_22-25-58](https://user-images.githubusercontent.com/6376135/79468327-61283800-8031-11ea-8dc9-938a2125aaf6.png)

**Comment by Sheldonsix** [comment]
> 说明外网是通的，比较有可能的是百度云服务器出现了问题
> ![2020-04-16_22-25-58](https://user-images.githubusercontent.com/6376135/79468327-61283800-8031-11ea-8dc9-938a2125aaf6.png)

好的，谢谢你

**Comment by Sheldonsix** [comment]
重试了 n 次，终于登上了，应该就是百度服务器的问题，感谢耐心解答🙏
