### ISSUE TITLE
关于 docker 速度问题

### ISSUE THREAD

**Issue by wmjlxl** [john-shine/Docker-CodeWeavers_CrossOver-VNC#35]
大佬，

我在群晖装了你的 docker， 可以用，很不错。首先非常感谢你。

然后我尝试对比一下 docker 的速度和 直接 运行百度云客户端对比。

发现 docker 的速度明显低于直接客户端下载，请问有什么可以优化的么？
例如端口之类的？

谢谢。

**Comment by john-shine** [comment]
没什么可以优化的，如果docker容器没有资源限制，影响下载速度的主要还是百度服务器的决策
