### ISSUE TITLE
迅雷这个镜像还能用吗？

### ISSUE THREAD

**Issue by flybluewolf** [john-shine/Docker-CodeWeavers_CrossOver-VNC#36]
我测试下来目前能迅雷账号登录，但是添加任何bt种子，都显示下载任务失败

**Comment by john-shine** [comment]
此迅雷版本比较老，可能是种子被屏蔽或者不支持的格式

**Comment by flybluewolf** [comment]
> 此迅雷版本比较老，可能是种子被屏蔽或者不支持的格式

哪里能找到迅雷新版本的包？我看crossover论坛上说thunder5没问题，但7不行

**Comment by john-shine** [comment]
thunder7无法兼容，无法运行
