### ISSUE TITLE
请问能否实现代理下载？

### ISSUE THREAD

**Issue by Sheldonsix** [john-shine/Docker-CodeWeavers_CrossOver-VNC#37]
主机在国外，连百度云的服务器比较慢，考虑能否通过代理的方式来下载百度网盘中的文件

**Comment by john-shine** [comment]
实现起来比较麻烦，没有网络通信和linux基础，比较难搞定
由于客户端不支持代理配置，所以需要配置网络层或更下层的代理如vpn，不能使用传输层的代理如socks

**Comment by Sheldonsix** [comment]
> 实现起来比较麻烦，没有网络通信和linux基础，比较难搞定
> 由于客户端不支持代理配置，所以需要配置网络层或更下层的代理如vpn，不能使用传输层的代理如socks

好的，谢谢回复
