### ISSUE TITLE
关于下载缓存位置的疑问

### ISSUE THREAD

**Issue by yyysuo** [john-shine/Docker-CodeWeavers_CrossOver-VNC#38]
非常感谢您提供了这么棒的解决方案，我有一个疑问，如果您方便的话帮忙解答一下。
使用环境：ESXI+Koolshare LEDE Docker+ Docker-CodeWeavers_CrossOver-VNC 
以上都装在SSD上，下载目录映射到10T的机械硬盘，您的这个方案，是直接下载文件到映射的机械硬盘，还是缓存文件到一定大小之后分次写入呢？如果是分次写入的话，缓存位置是在内存还是SSD上，会增加SSD的写入量吗？

**Comment by john-shine** [comment]
这个属于下载客户端的问题，不过一般来讲是直接写入的，不是到一定大小之后分批再写入，因为下载文件并不一定是连续的，也有可能是跳跃式的下载

**Comment by yyysuo** [comment]
> 这个属于下载客户端的问题，不过一般来讲是直接写入的，不是到一定大小之后分批再写入，因为下载文件并不一定是连续的，也有可能是跳跃式的下载

多谢解惑
