### ISSUE TITLE
关于下载位置

### ISSUE THREAD

**Issue by master-ang** [john-shine/Docker-CodeWeavers_CrossOver-VNC#39]
你好，我绑定了下载文件夹，可是尝试下载后，下载成功了，但我的绑定文件夹内却是空的，也不知到下载文件去哪了？

**Comment by master-ang** [comment]
找到了，没有映射，在创建的docker里面，这是怎么回事？
/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/2e45251a6fae3b5bbb54be89a3d7b19f9aed484d062803439402e12eec5d986f/diff/home/baidu/baidunetdiskdownload

**Comment by master-ang** [comment]
已经解决，映射到/home/baidu/baidunetdiskdownload这个目录搞定的，而不是/mnt/drive_d

**Comment by john-shine** [comment]
好的，这块我会更新下README说明
