### ISSUE TITLE
百度云普通会员无法下载

### ISSUE THREAD

**Issue by AlliotTech** [john-shine/Docker-CodeWeavers_CrossOver-VNC#41]
突然发现普通会员的话 无法添加下载任务（点击下载没有反映），换成普通用户就可以添加下载了。

**Comment by john-shine** [comment]
可能是因为是rar等压缩文件，选择后使用上面的下载按钮，或者使用右键菜单

**Comment by AlliotTech** [comment]
点击上面也是 这个尝试过了   非压缩文件也是。。

**Comment by john-shine** [comment]
我也是普通会员帐号，尝试很多次也没有复现出来你说的这种情况，难判断是什么问题
