### ISSUE TITLE
请问为何宿主机的下载目录里没有下载的文件？

### ISSUE THREAD

**Issue by msn1983aa** [john-shine/Docker-CodeWeavers_CrossOver-VNC#42]
创建容器的时候已经绑定了宿主机文件目录到/mnt/drive_d，但是文件下载完毕后宿主机目录是空的，通过sudo docker exec -it $container_id /bin/bash之后可以看到文件确实在baidunetdiskdownload文件夹内，只是宿主机目录里看不到

**Comment by msn1983aa** [comment]
已经确认过，文件确实在容器里，也没有出现下载错误，下载的文件都用
创建容器的时候用的-v /path/to/download/folder:/mnt/drive_d

**Comment by john-shine** [comment]
/mnt/drive_d需要修改为/home/baidu/baidunetdiskdownload

**Comment by msn1983aa** [comment]
> /mnt/drive_d需要修改为/home/baidu/baidunetdiskdownload

我一般都不去动容器内的路径，所以没反应过来，谢谢指教！

这个度盘下载真的很好用，又不违规，谢谢分享

**Comment by john-shine** [comment]
不客气的
