### ISSUE TITLE
关于微博等第三方账号登陆百度云

### ISSUE THREAD

**Issue by tonytt99** [john-shine/Docker-CodeWeavers_CrossOver-VNC#43]
你好，感谢发布这个镜像。
请问，这个镜像可以使用微博等第三方软件登陆吗？我看 README.md 的1.1中提到”修复第三方登录“，具体应该怎么操作。谢谢！

**Comment by john-shine** [comment]
之前是windows的客户端在crossover中运行，有第三方登录。现在是linux版的客户端，官方没有提供第三方登录

**Comment by tonytt99** [comment]
好的，感谢回复。
