### ISSUE TITLE
首次使用没问题，但是第二次使用打开百度网盘是白屏，不显示登录界面

### ISSUE THREAD

**Issue by MIMONATCH** [john-shine/Docker-CodeWeavers_CrossOver-VNC#45]
重新拉镜像，重新开启应用问题依旧    
![rt](https://imgdata.xiaoblogs.cn/1.png)

**Comment by sun47451685** [comment]
可以试试2.1更新的指令来重置

**Comment by MIMONATCH** [comment]
感谢感谢

**Comment by john-shine** [comment]
在容器内中~/baidunetdiskdownload/目录下添加.reset文件夹，重置百度云客户端设置
