### ISSUE TITLE
Something went wrong, connection is closed

### ISSUE THREAD

**Issue by morecrazyang** [john-shine/Docker-CodeWeavers_CrossOver-VNC#46]
![image](https://user-images.githubusercontent.com/9960469/87400608-a0900180-c5eb-11ea-8340-265f11a15530.png)
啥都配置好了，外网访问就这样了，十分十分想使用这个套件配合docker，求救！~

**Comment by john-shine** [comment]
外网访问还需要配置WebSocket访问，可以chrome网页右键->检查，看下网络请求报错

**Comment by fucao** [comment]
遇到同样的问题，请问怎么解决呢?
![image](https://user-images.githubusercontent.com/15061002/91957535-be026180-ed38-11ea-8a5b-2e0c5747226c.png)

**Comment by fucao** [comment]
遇到同样的问题请问怎么解决呢？
![image](https://user-images.githubusercontent.com/15061002/91957681-f0ac5a00-ed38-11ea-8a51-64dad985da0e.png)

**Comment by john-shine** [comment]
@fucao  这个不是同一个问题，你这个已经连接上了，但是桌面是黑屏，可以右键点击看看有没有菜单
