### ISSUE TITLE
百度网盘版本更新了，我重新build的一个镜像发现没有百度网盘登录页面

### ISSUE THREAD

**Issue by zybug** [john-shine/Docker-CodeWeavers_CrossOver-VNC#48]
由于shell 水平一般、novnc 没有怎么接触，所以写死了百度网盘版本为最新版本http://wppkg.baidupcs.com/issue/netdisk/Linuxguanjia/3.3.2/baidunetdisk-3.3.2.x86_64.rpm，重新build 镜像成功，远程桌面发现没有百度网盘登录页面，希望能帮忙修复一下这个问题，感谢。

**Comment by john-shine** [comment]
好的，这周修复
