### ISSUE TITLE
IDM for Docker会自动创建无效的软链接

### ISSUE THREAD

**Issue by Zyx-A** [john-shine/Docker-CodeWeavers_CrossOver-VNC#5]
使用-v参数设置共享目录后，会在该目录下创建一个【drive_d -> /mnt/drive_d】的软链接，请作者看看能否删除掉

**Comment by john-shine** [comment]
哪个链接，能否截图看看

**Comment by john-shine** [comment]
哪个目录，能否截图看看

**Comment by Zyx-A** [comment]
[http://i2.bvimg.com/541560/df53656a5b5e2918.png](url)

sudo docker run -d -p 5901:5901 --name idm -v ~/Downloads/BaiduNetdiskDownload:/mnt/drive_d johnshine/idm-crossover-vnc:latest

**Comment by john-shine** [comment]
抱歉，拖得有点久，已修复

**Comment by Zyx-A** [comment]
3Q，非常感谢！
