### ISSUE TITLE
Use of uninitialized value $proto in socket

### ISSUE THREAD

**Issue by icksky** [john-shine/Docker-CodeWeavers_CrossOver-VNC#52]
VNC客户端连接不上 容器有以下日志 是否正常启动了呢?
```
Please be aware that you are exposing your VNC server to all users on the,
local machine. These users can access your server without authentication!,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
,
New '2e19e0d10b99:1 (baidu)' desktop at :1 on machine 2e19e0d10b99,
,
Starting applications specified in /home/baidu/.vnc/xstartup,
Log file is /home/baidu/.vnc/2e19e0d10b99:1.log,
,
Use xtigervncviewer -SecurityTypes None,TLSNone :1 to connect to the VNC server.,
,
```

**Comment by john-shine** [comment]
更新为最新版本的镜像再看下

**Comment by icksky** [comment]
已经用的 `johnshine/baidunetdisk-crossover-vnc:3.1` 了 之前旧版好像也有这个问题. 不知道是不是我环境问题

**Comment by john-shine** [comment]
应该是。主机系统环境，docker版本，内核版本这些信息提供下

**Comment by john-shine** [comment]
novnc能不能链接，现在版本的vncserver默认绑定到了localhost，会导致远程连接不上

**Comment by icksky** [comment]
操作系统: `Openmediavault 5.5.9-1`
内核: `Linux version 5.4.60-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.60-1 (Mon, 31 Aug 2020 10:36:22 +0200)`
Docker: `Docker version 19.03.12, build 48a66213fe`

环境问题估计就不好处理了. 远程无法连接 不知道如何修改可远程连接的模式.

**Comment by john-shine** [comment]
![image](https://user-images.githubusercontent.com/6376135/93050250-1fa9c080-f695-11ea-8eb3-ee2b39a0985f.png)
我看系统没有你这个版本，最新的只有5.3.9

**Comment by icksky** [comment]
安装后程序自动升级的. 发布出来的没有这个版本. 太感谢了 这么有心

**Comment by flcl** [comment]
我群晖上的docker用最新版也连不上 日志和楼主一样

**Comment by shinn32** [comment]
同样的问题，群晖6.2.3用latest版本novnc的web界面一片灰，登陆界面根本看不到，回退到3.1就可以了。

**Comment by iamsuperark** [comment]
症状：
VNC无法连接
“the connection closed unexpectedly" 

环境及报错如下：


黑裙版本：
Linux InterStella 3.10.105 #23739 SMP Tue Jul 3 19:50:10 CST 2018 x86_64 GNU/Linux synology_broadwell_3617xs

image使用3.1版本


docker启动日志：


date | stream | content
-- | -- | --
2021-06-22 03:51:10 | stdout |  
2021-06-22 03:51:10 | stdout | Use xtigervncviewer -SecurityTypes None,TLSNone :1 to connect to the VNC server.
2021-06-22 03:51:10 | stdout |  
2021-06-22 03:51:10 | stdout | Log file is /home/baidu/.vnc/e46de3af6379:1.log
2021-06-22 03:51:10 | stdout | Starting applications specified in /home/baidu/.vnc/xstartup
2021-06-22 03:51:10 | stdout |  
2021-06-22 03:51:10 | stdout | New 'e46de3af6379:1 (baidu)' desktop at :1 on machine e46de3af6379
2021-06-22 03:51:10 | stdout |  
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
2021-06-22 03:51:10 | stderr | local machine. These users can access your server without authentication!
2021-06-22 03:51:10 | stderr | Please be aware that you are exposing your VNC server to all users on the

VNC Mac版本：6.21.406

容器日志：

root@InterStella:/volume1/homes/baidu/baidunetdiskdownload# docker exec boring_goldwasser tail ./.vnc/e46de3af6379:1.log

    http://e46de3af6379:6080/vnc.html?host=e46de3af6379&port=6080

Press Ctrl-C to exit


Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value

**Comment by ChuangYu1897** [comment]
**novnc（6080）可以连接，VNC（5901）连接不了，请问是什么问题以及如何解决**

**系统版本**：OMV 5.6.14-1 (Usul)
**内核版本**：Linux version 5.10.0-0.bpo.7-amd64 (debian-kernel@lists.debian.org) (gcc-8 (Debian 8.3.0-6) 8.3.0, GNU ld (GNU Binutils for Debian) 2.31.1) #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04)
**Docker**：Docker version 20.10.8, build 3967b7d
**镜像**：安装时默认为latest
**日志**：
Please be aware that you are exposing your VNC server to all users on the,
local machine. These users can access your server without authentication!,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.,
,
New 'c16626212fe2:1 (baidu)' desktop at :1 on machine c16626212fe2,
,
Starting applications specified in /home/baidu/.vnc/xstartup,
Log file is /home/baidu/.vnc/c16626212fe2:1.log,
,
Use xtigervncviewer -SecurityTypes None,TLSNone :1 to connect to the VNC server.,

**Comment by john-shine** [comment]
issue标题的报错属于warning级别错误，不影响程序的运行，5901端口连不上是因为VNC绑定到了localhost，最新的镜像已修改
