### ISSUE TITLE
VNC连接需要用户名、密码，noVNC正常

### ISSUE THREAD

**Issue by primovist** [john-shine/Docker-CodeWeavers_CrossOver-VNC#53]
使用iOS客户端Screens/RealVNC Viewer，前者要求输入用户名/密码后者连接不上。但是网页打开可以见到百度网盘已经运行。

**Comment by primovist** [comment]
百度网盘出现这个问题。CrossOver正常可以连接。

**Comment by john-shine** [comment]
tigervnc新版本默认绑定到了localhost，导致外面连接不上，网页不能满足要求？

**Comment by primovist** [comment]
> tigervnc新版本默认绑定到了localhost，导致外面连接不上，网页不能满足要求？

也可以，我按照readme操作发现不可以，看了Dockerfile才提了issues。
感谢回复。
另：Readme最好可以修改一下。

**Comment by primovist** [comment]
依然使用VNC客户端的方法也找到了，添加- localhost=no，重新build了一个docker image。
