### ISSUE TITLE
不能登录账号，提示版本过低无法使用

### ISSUE THREAD

**Issue by wangguojing** [john-shine/Docker-CodeWeavers_CrossOver-VNC#56]
登陆上马上提示账号已过期，然后回到登陆界面，还有提示版本低。用的最新的docker镜像，还是一样，可能是内置网盘版本比较低，请问如何解决。

**Comment by john-shine** [comment]
https://github.com/john-shine/synology-baiduNetdisk-package/issues/27#issuecomment-700475612
