### ISSUE TITLE
登陆后提示账号过期，同时提示检测到新版本

### ISSUE THREAD

**Issue by msn1983aa** [john-shine/Docker-CodeWeavers_CrossOver-VNC#58]
2020-10-16

账号过期的提示无限循环，登陆-过期-登出-登陆

还请大佬更新一下

**Comment by Dicky-L** [comment]
遇到同样的问题

**Comment by xiaominglei001** [comment]
同问，一开始还好用，现在就是： 账号过期的提示无限循环，登陆-过期-登出-登陆

**Comment by xiaominglei001** [comment]
> 同问，一开始还好用，现在就是： 账号过期的提示无限循环，登陆-过期-登出-登陆

解决了，换了个映像，注意下文件夹权限配置和系统版本，谁有需要可参考这里 https://github.com/gshang2017/docker/issues/43

**Comment by msn1983aa** [comment]
> > 同问，一开始还好用，现在就是： 账号过期的提示无限循环，登陆-过期-登出-登陆
> 
> 解决了，换了个映像，注意下文件夹权限配置和系统版本，谁有需要可参考这里 [gshang2017/docker#43](https://github.com/gshang2017/docker/issues/43)

果然好使
Thanks♪(･ω･)ﾉ

**Comment by john-shine** [comment]
恩，最近看了最新版DSM内核已经升级，已经可以支持最新版百度网盘。目前项目上已经更新掉。
