### ISSUE TITLE
ubuntu 16.04 安装，vncviewer无法连接

### ISSUE THREAD

**Issue by yuritry** [john-shine/Docker-CodeWeavers_CrossOver-VNC#59]
sudo docker run -d  --name=baidupan -p 5901:5901  -v /home/baidu/baidunetdiskdownload:/home/baidu/baidunetdiskdownload/ johnshine/baidunetdisk-crossover-vnc:latest

容器运行正常，但vnc无法连接： vncserver closed connection.

root@vps:~# docker logs 0830
Please be aware that you are exposing your VNC server to all users on the
local machine. These users can access your server without authentication!
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.
Use of uninitialized value $proto in socket at /usr/bin/vncserver line 355.

New '0830a5d540e9:1 (baidu)' desktop at :1 on machine 0830a5d540e9

Starting applications specified in /home/baidu/.vnc/xstartup
Log file is /home/baidu/.vnc/0830a5d540e9:1.log

Use xtigervncviewer -SecurityTypes None,TLSNone :1 to connect to the VNC server.

**Comment by ptman-boy** [comment]
同样无法使用vnc连接，浏览器上用另一端口可配置

**Comment by rong280** [comment]
我也是这样，用的最新版那个镜像，容器运行和端口映射都正常，但是VNC无法连接

**Comment by bigfoxtail** [comment]
@rong280 @ptman-boy  映射出6080端口，然后直接浏览器访问6080端口试试，应该可以看到web的vnc界面，我估计是已经通过webvnc连接了服务，其他的vnc客户端无法连接进去

**Comment by john-shine** [comment]
将容器内的启动文件：/entrypoint.sh
```
if [ -z $vnc_password ]; then
    /usr/bin/vncserver -geometry 1920x1080 -fg -SecurityTypes None,TLSNone
else
    /usr/bin/vncserver -geometry 1920x1080 -fg
fi
```
修改为

```
if [ -z $vnc_password ]; then
    /usr/bin/vncserver -localhost no -geometry 1920x1080 -fg -SecurityTypes None,TLSNone
else
    /usr/bin/vncserver -localhost no -geometry 1920x1080 -fg
fi
```
即可从远程连接
