### ISSUE TITLE
DSM7.0

### ISSUE THREAD

**Issue by eepocket** [john-shine/Docker-CodeWeavers_CrossOver-VNC#60]
好像是spk不支持dsm7.0吧？ 安装了下报了lower privilege。
docker里装好了，但是用vnc去连接5901端口连接不上，不知道是怎么了。

**Comment by john-shine** [comment]
@eepocket 是的，没有在dsm7.0下开发测试，不支持dsm7

**Comment by lostwindsenril** [comment]
不是的，SPK是不支持7.0，但docker镜像可以用
VNC连接不上是作者的entrypoint.sh配错了，直接连接6080即可。
如果一定要用vnc，可以把entrypoint拷出来修改，在运行/usr/bin/vncserver的命令后加上-localhost no --I-KNOW-THIS-IS-INSECURE，同时也可以修改分辨率，1024x768足够了。

**Comment by lostwindsenril** [comment]
> 不是的，SPK是不支持7.0，但docker镜像可以用 VNC连接不上是作者的entrypoint.sh配错了，直接连接6080即可。 如果一定要用vnc，可以把entrypoint拷出来修改，在运行/usr/bin/vncserver的命令后加上-localhost no --I-KNOW-THIS-IS-INSECURE，同时也可以修改分辨率，1024x768足够了。

6080是web端口，直接浏览器打开
