### ISSUE TITLE
Linux version 5.4.0 Ubuntu 9.3.0

### ISSUE THREAD

**Issue by djbone** [john-shine/Docker-CodeWeavers_CrossOver-VNC#63]
Linux version 5.4.0-29-generic (buildd@lgw01-amd64-035) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020
好像用不了，怎么破？

**Comment by john-shine** [comment]
@djbone 使用的ubuntu发行版本号是 20.04 LTS吗？
