### ISSUE TITLE
一脸蒙蔽的路过...

### ISSUE THREAD

**Issue by passioncsu** [john-shine/Docker-CodeWeavers_CrossOver-VNC#65]
作者的readme一直提映射5901端口通过vncviewer访问操作,本来也是理解的奈何. vnc一直没法访问, 直接被拒绝, 可能有啥其他的坑也没仔细查, exec进去发现起了webvnc   有6080端口,  映射出来直接能用,

所以readme里为啥不提映射6080端口, 这样非常方便啊.

docker run -d -p 6080:6080 -e vnc_password=123456 --name baidudisk -v `pwd`/baidunetdiskdownload:/home/baidu/baidunetdiskdownload/ johnshine/baidunetdisk-crossover-vnc:latest

**Comment by john-shine** [comment]
历史更新的原因，5901最早默认是绑定到0.0.0.0的，后来版本更新绑定到了localhost就无法访问了，也没去更新。6080是群晖套件里面做的一个版本，所以没在这里更新。现在README已经更新了
