### ISSUE TITLE
不能使用vnc客户端连接

### ISSUE THREAD

**Issue by yefeiyu** [john-shine/Docker-CodeWeavers_CrossOver-VNC#66]
刚看到大大更新了。
顺便问一下，安装使用后，不能使用客户端连接。是5901在你的Dockerfile文件中设置为127.0.0.1:5901而导致不能远程（我是远程ddns连接的群晖安装的本docker）使用只能本地使用的原故呢，抑或还是其他原因呢？
在论坛里也讨论了这个问题，有使用者反馈只有2.1版本之前正常。
望赐教。

**Comment by ttimasdf** [comment]
开发者配置错了。通过下面的方法修复。

```sh
docker exec -i -t baiduyun sudo sed -i -e 's/-fg/-fg -localhost no/g' /entrypoint.sh
docker restart <your container name>  # 重启容器
```

你也可以写一个 Dockerfile 将上面的命令固化到一个镜像中。我个人是没啥需求。
