### ISSUE TITLE
CrossOver试用版

### ISSUE THREAD

**Issue by buyijunchen** [john-shine/Docker-CodeWeavers_CrossOver-VNC#7]
我买了一个许可，没法下载到docker容器中去

**Comment by buyijunchen** [comment]
\u8fd9\u662f\u4e00\u4e2a\u6709\u65f6\u95f4\u9650\u5236\u7684 CrossOver \u8bd5\u7528\u7248\u3002
\u8bf7\u8bbf\u95ee store.codeweavers.com \u4ee5\u8d2d\u4e70\u4e00\u4e2a CrossOver \u4f7f\u7528\u8bb8\u53ef\u3002
\u5982\u679c\u60a8\u5df2\u7ecf\u8d2d\u4e70\u4e86\u4f7f\u7528\u8bb8\u53ef\uff0c\u8bf7\u8f93\u5165\u60a8\u7684 codeweavers.com \u8d26\u53f7\u90ae\u7bb1\u53ca\u5bc6\u7801\uff0c\u4ee5\u89e3\u9501 CrossOver\u3002

**Comment by buyijunchen** [comment]
显示：注册失败，无法下载一个合法的许可文件

**Comment by john-shine** [comment]
现在本地电脑上下载许可文件，然后映射到docker container中。
你是如何下载许可文件的，上面的失败提示是在哪里展示的？

**Comment by buyijunchen** [comment]
我用的是tinyVNC，一连上就说CrossOver已过期。怎么映射？

**Comment by buyijunchen** [comment]
tightVNC

**Comment by buyijunchen** [comment]
应该是在docker container里的crossover里下载的，权限问题吧

**Comment by buyijunchen** [comment]
看到你的readme了，我试试映射

**Comment by buyijunchen** [comment]
还是不行，我用的是CrossOver for linux 17的license，应该没问题吧

**Comment by buyijunchen** [comment]
license装载一个文件夹，而不是分别装载两个文件，是不是比较好？
不过我映射了这两个文件，还是没用。

**Comment by john-shine** [comment]
docker cp johnshine-baidunetdisk-crossover-vnc1:"/home/crossover/.vnc/johnshine-baidunetdisk-crossover-vnc1:1.log" . 
然后看看 johnshine-baidunetdisk-crossover-vnc1:1.log 里面的日志内容

**Comment by john-shine** [comment]
也可以 docker exec -it johnshine-baidunetdisk-crossover-vnc1 /bin/bash 
进入到docker中查看错误信息

**Comment by buyijunchen** [comment]
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc TigerVNC 1.8.0 - built Aug  7 2017 01:32:32
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11903000, The X.Org Foundation


Fri Apr 13 09:52:46 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
sudo: unable to send audit message: Unknown error -1
sudo: unable to send audit message: Unknown error -1
sudo: unable to send audit message: Unknown error -1
ln: failed to create symbolic link ‘/BaiduNetdiskDownload’: Permission denied

**Comment by buyijunchen** [comment]
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc TigerVNC 1.8.0 - built Aug  7 2017 01:32:32
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11903000, The X.Org Foundation


Fri Apr 13 10:25:04 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
sudo: unable to send audit message: Unknown error -1
sudo: unable to send audit message: Unknown error -1
sudo: unable to send audit message: Unknown error -1
ln: failed to create symbolic link ‘/BaiduNetdiskDownload’: Permission denied

**Comment by buyijunchen** [comment]
/BaiduNetdiskDownload，我看到这个文件夹了，权限怎么改也还是这个信息，1.log里的内容全在这儿了

**Comment by buyijunchen** [comment]
问题解决了，我的license文件夹的权限问题，但是好像键盘没法输入。

**Comment by buyijunchen** [comment]
你的latest版本似乎比1.2旧啊，镜像太慢，多次不成功

**Comment by john-shine** [comment]
@buyijunchen 1.2版本是晚上无意中推送成功的，latest还没有更新；
权限问题明天修复下。

**Comment by buyijunchen** [comment]
我都搞好了，谢谢。不过你的程序还有bug，D盘能看不能用，只能用Y盘。发自我的华为手机-------- 原始邮件 --------主题：Re: [john-shine/Docker-CodeWeavers_CrossOver-VNC] CrossOver试用版 (#7)发件人：John Shine 收件人：john-shine/Docker-CodeWeavers_CrossOver-VNC 抄送：buyijunchen ,Mention @buyijunchen 1.2版本是晚上无意中推送成功的，latest还没有更新；
权限问题明天修复下。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/john-shine/Docker-CodeWeavers_CrossOver-VNC","title":"john-shine/Docker-CodeWeavers_CrossOver-VNC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@john-shine in #7: @buyijunchen 1.2版本是晚上无意中推送成功的，latest还没有更新；\r\n权限问题明天修复下。"}],"action":{"name":"View Issue","url":"https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/issues/7#issuecomment-381195828"}}}
