### ISSUE TITLE
Crossover版本问题

### ISSUE THREAD

**Issue by freefrank** [john-shine/Docker-CodeWeavers_CrossOver-VNC#8]
感谢作者制作这个镜像！
请问自带crossover版本是什么呢？我购买的是17版本的crossover，无法激活。

**Comment by freefrank** [comment]
莫名其妙又可以激活了，用root 在/opt/cxoffice/bin/cxregister 激活的。谢谢！

**Comment by john-shine** [comment]
好的，不客气。
