### ISSUE TITLE
baidunetdisk的 entrypoint.sh  没有修改

### ISSUE THREAD

**Issue by ashesofdream** [john-shine/Docker-CodeWeavers_CrossOver-VNC#80]
参见 issue ：https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/issues/66

docker pull下来的镜像，仍然需要手动修改vnc启动命令附加 -localhost no

**Comment by ashesofdream** [comment]
https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/pull/81

**Comment by john-shine** [comment]
感谢提出问题，这个是因为百度网盘的镜像使用的是自己的[entrypoint.sh](https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/blob/master/BaiduNetdisk/entrypoint.sh)，没有使用基础镜像的entrypoint.sh，稍后会更新相关文件
