### ISSUE TITLE
BUG: 无限认证失败

### ISSUE THREAD

**Issue by yuzhen1024** [john-shine/Docker-CodeWeavers_CrossOver-VNC#85]
类似 https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/issues/2
用的是 https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/tree/master/Thunder
tiger vnc可以登陆，其它常规的linux vnc客户端是KRDC和gnome-connections则无法登陆，不管是空密码还是存在密码的情况。

使用tiger还有一个问题就是:
![](https://img-blog.csdnimg.cn/eb2f5bdfefa14a839dd51c4559afff92.png)

希望可以像 https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/tree/master/BaiduNetdisk 使用novnc。

**Comment by john-shine** [comment]
因为服务端使用的是tigervnc，所以客户端还是得用tigervnc连接，其它客户端会有协议不兼容的问题。
Thunder镜像问题比较多，后续不计划更新，也没有适配novnc的计划。
试用版问题属于软件著作权问题，这里无法解决。
