### ISSUE TITLE
群晖设置了反向代理访问，显示Something went wrong,connection is closed

### ISSUE THREAD

**Issue by irondududu** [john-shine/Docker-CodeWeavers_CrossOver-VNC#86]
但是不通过代理访问仍然可以正常使用，这是为何呢
这个是正常通过端口访问：
![image](https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/assets/168980920/de29c5ed-36c4-4565-abf0-ce3534d68467)

这个是通过群晖反向代理之后访问：
![image](https://github.com/john-shine/Docker-CodeWeavers_CrossOver-VNC/assets/168980920/c691255a-9070-4b1a-a999-f747468031ad)

**Comment by john-shine** [comment]
可以参考此文章解决：https://wp.gxnas.com/9311.html

**Comment by irondududu** [comment]
感谢大佬，已解决！
